version: "2.2"
services:
  producer:
    image: node:12
    container_name: producer
    command: bash -c "npm install && npm start"
    volumes:
       - "./producer:/app"
    working_dir: "/app"
    cpuset: '1'
    cpu_percent: 10


  consumer:
    image: clojure:openjdk-8-lein
    container_name: consumer
    command: bash -c "lein clean && lein compile && lein run"
    volumes:
       - "./consumer:/app"
    working_dir: "/app"
    ports:
      - "3001:3001"
    cpuset: '1'
    cpu_percent: 10
    

  client:
    image: node:12
    container_name: client
    command: bash -c "npm install && npm start"
    volumes:
       - "./client:/app"
    working_dir: "/app"
    ports:
      - "3002:3002"
    cpuset: '1'
    cpu_percent: 10
